language: php

sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: '7.3'
    - env: DBTYPE=mysql; MW=1.31.0
      php: '7.0'
  fast_finish: true

install: bash .travis.install.sh

script: ../phase3/tests/phpunit/phpunit.php -c ../phase3/vendor/mediawiki/doctrine-connection/phpunit.xml.dist

cache:
  directories:
    - $HOME/.composer/cache
